export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR'

export const SET_STATE = 'SET_STATE'
export const SET_DATA = 'SET_DATA'

export const UPDATE_PRODUCT_QUANTITY_USED = 'UPDATE_PRODUCT_QUANTITY_USED'
export const UPDATE_PRODUCT_QUANTITY_ORDERED = 'UPDATE_PRODUCT_QUANTITY_ORDERED'
export const SET_PRODUCT_QUANTITY = 'SET_PRODUCT_QUANTITY'